name       : racket
version    : '7.5'
release    : 10
source     :
    - https://mirror.racket-lang.org/installers/7.5/racket-7.5-src-builtpkgs.tgz : de9609d14322aea911c0017b0518aaca5b2e418038c5c2edb475a8fdb5ba688b
license    : GPL-3.0
component  : programming
libsplit   : no
summary    : Racket is a full-spectrum Lisp/Scheme-family programming language.
description: |
    Racket is a full-spectrum programming language. It goes beyond Lisp and Scheme with dialects that support objects, types, laziness, and more.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libffi)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - libjpeg-turbo-devel
    - urw-core35-fonts
setup      : |
    # This patch series ensures that we can configure racket-7.5 w/--enable-shared
    # -- this bug should be fixed in racket-7.6.
    %patch -p2 -i $pkgfiles/0001-configure-fix-schver.h-parsing.patch
    %patch -p2 -i $pkgfiles/0002-Separate-GCC-and-GNU-Make-detection-2902.patch
    %patch -p2 -i $pkgfiles/0003-Improve-gcc-detection-in-configure-script-2897.patch
    cd src
    %configure --enable-shared --disable-libs
build      : |
    cd src
    %make
install    : |
    cd src
    %make_install
    mkdir -p $installdir/usr/share/icons/hicolor/{16x16,32x32,48x48,256x256}/apps
    cp ../share/pkgs/icons/plt-16x16.png $installdir/usr/share/icons/hicolor/16x16/apps/drracket.png
    cp ../share/pkgs/icons/plt-32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/drracket.png
    cp ../share/pkgs/icons/plt-48x48.png $installdir/usr/share/icons/hicolor/48x48/apps/drracket.png
    cp ../share/pkgs/icons/plt-logo-red-diffuse.png  $installdir/usr/share/icons/hicolor/256x256/apps
    mv $pkgfiles/drracket.desktop $installdir/usr/share/applications/
    # Remove empty directories
    find $installdir -type d -empty -delete
