name       : racket
version    : '8.0'
release    : 15
source     :
    - https://mirror.racket-lang.org/installers/8.0/racket-8.0-src-builtpkgs.tgz : 54093909451eb4f2b2b100d93f2f3c5f2d29a54700e26ed127677328143a0792
license    :
    - Apache-2.0
    - LGPL-3.0-only
    - MIT
component  : programming
libsplit   : no
summary    : Racket is a full-spectrum Lisp/Scheme-family programming language.
description: |
    Racket is a full-spectrum programming language. It goes beyond Lisp and Scheme with dialects that support objects, types, laziness, and more.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libffi)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
    - libjpeg-turbo-devel
    - urw-core35-fonts
setup      : |
    # Without --enable-useprefix, racket-7.6+ does an in-place build
    cd src
    %configure \
        --enable-useprefix \
        --enable-shared \
        --disable-libs
build      : |
    cd src
    # ensure that the racket build system uses all available CPU threads
    %make CPUS=%YJOBS%
install    : |
    cd src
    %make_install
    mkdir -p $installdir/usr/share/icons/hicolor/{16x16,32x32,48x48,256x256}/apps
    cp ../share/pkgs/icons/plt-16x16.png $installdir/usr/share/icons/hicolor/16x16/apps/drracket.png
    cp ../share/pkgs/icons/plt-32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/drracket.png
    cp ../share/pkgs/icons/plt-48x48.png $installdir/usr/share/icons/hicolor/48x48/apps/drracket.png
    cp ../share/pkgs/icons/plt-logo-red-diffuse.png  $installdir/usr/share/icons/hicolor/256x256/apps
    cp $pkgfiles/drracket.desktop $installdir/usr/share/applications/
    # Remove empty directories
    find $installdir -type d -empty -delete
