name       : racket
version    : '8.9'
release    : 19
source     :
    - https://mirror.racket-lang.org/installers/8.9/racket-8.9-src-builtpkgs.tgz : 5727a69cb70f8b4d237e105669b019028f07e7de5f3196c994d0331215045b7f
license    :
    - Apache-2.0
    - LGPL-3.0-only
    - MIT
component  : programming
libsplit   : no
strip      : no  # mred and mzscheme will break if they're stripped
summary    : Racket is a full-spectrum Lisp/Scheme-family programming language.
description: |
    Racket is a full-spectrum programming language. It goes beyond Lisp and Scheme with dialects that support objects, types, laziness, and more.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liblz4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sqlite3)
    - urw-core35-fonts
setup      : |
    # upstream recommends against building shared libraries (--enable-shared)
    mkdir -p src/build
    pushd src/build
    ../%configure \
        --enable-libz \
        --enable-liblz4
    popd
build      : |
    pushd src/build
    # ensure that the racket build system uses all available CPU threads
    %make CPUS=%YJOBS%
    popd
install    : |
    pushd src/build
    %make_install
    mkdir -p $installdir/usr/share/icons/hicolor/{16x16,32x32,48x48,256x256}/apps
    cp ../../share/pkgs/icons/plt-16x16.png $installdir/usr/share/icons/hicolor/16x16/apps/drracket.png
    cp ../../share/pkgs/icons/plt-32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/drracket.png
    cp ../../share/pkgs/icons/plt-48x48.png $installdir/usr/share/icons/hicolor/48x48/apps/drracket.png
    cp ../../share/pkgs/icons/plt-logo-red-diffuse.png  $installdir/usr/share/icons/hicolor/256x256/apps
    cp $pkgfiles/drracket.desktop $installdir/usr/share/applications/
    # Remove empty directories
    find $installdir -type d -empty -delete
    popd
