name       : racket
version    : 6.3
release    : 1
source     :
    - http://mirror.racket-lang.org/installers/6.3/racket-minimal-6.3-src.tgz : 511b8c61c7e6f51d06fdc1b07dff5a4ad0d9c06676a623d6c1820bc6d0e6ac1a
license    : GPL-3.0
summary    : Racket is a full-spectrum programming language.
description: |
    Racket is a full-spectrum programming language. It goes beyond Lisp and Scheme with dialects that support objects, types, laziness, and more.
builddeps   :
    - pkgconfig(cairo)
    - pkgconfig(libffi)
    - pkgconfig(pango)
    - pkgconfig(sqlite3) 
    - libjpeg-turbo-devel
setup      : |
    cd src
    %configure --disable-static
build      : |
    cd src
    %make
install    : |
    cd src
    %make_install
